site_name: Perceptrón Simple - Documentación
site_url: https://ejemplo.com/
site_author: Estudiante IA
site_description: Documentación del proyecto de Perceptrón Simple para Inteligencia Artificial

theme:
  name: material
  language: es
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - footnotes
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.insert(0, ".")
          selection:
            docstring_style: google
          rendering:
            show_source: true

nav:
  - Inicio: index.md
  - Arquitectura: arquitectura.md
  - API:
      - Perceptrón: api/perceptron.md
      - Utilidades: api/utils.md
  - Guía de Usuario: guia-usuario.md
  - Ejemplos: ejemplos.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/usuario/ia-perceptron 